# -*- coding: utf-8 -*-
"""Charts of Algorithm Data Type

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYC2MdbmuuEZSz-tZcSmuBA0if-zHX_p
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load your data
df = pd.read_csv('/content/algorithmdata_Datatype.csv')

data_type_counts = df['Data Type'].value_counts()
plt.figure(figsize=(8, 8))
data_type_counts.plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribution of Data Types')
plt.ylabel('')  # Optional: Remove y-axis label
plt.show()

data_type_counts = {
    'Alphanumeric': df['Alphanumeric'].sum(),
    'Geospatial': df['Geospatial'].sum(),
    'Image': df['Image'].sum(),
    'Audio': df['Audio'].sum()
}

# Convert to DataFrame for plotting
counts_df = pd.DataFrame(list(data_type_counts.items()), columns=['Data Type', 'Count'])

# Create the bar plot
plt.figure(figsize=(8, 5))
plt.bar(counts_df['Data Type'], counts_df['Count'])
plt.title('Count of Data Types')
plt.xlabel('Data Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()