# -*- coding: utf-8 -*-
"""AF_mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWr_tLwaJz0LQsDZE8Ce0sVuaFY6-d7s
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import spacy

# Load the occupational data
df = pd.read_excel('/content/sample_data/job_data_with_details.xlsx')

# Filter out rows where the 'Tasks' column is empty or NaN
df = df[df['Tasks'].notna() & df['Tasks'].str.strip().astype(bool)]

print(df.head())

# Load the spaCy model for NLP tasks
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
    if isinstance(text, str):
        # Tokenization, lemmatization, and lowercasing
        doc = nlp(text.lower())
        return " ".join([token.lemma_ for token in doc if not token.is_stop and not token.is_punct])
    else:
        # Return an empty string or handle NaN cases as needed
        return ""

# Apply preprocessing to the 'Tasks' column
df['processed_description'] = df['Tasks'].apply(preprocess)

# Display the processed descriptions
print(df['processed_description'].head())

# Modify the mapping function to allow multiple algorithm functions per task
def map_algorithm_function(description):
    description = description.lower()

    # List to store all applicable algorithm functions
    algorithm_functions = []

    # Check for different keywords and append respective algorithm functions
    if any(keyword in description for keyword in ['report', 'describe', 'summarize', 'overview', 'document', 'record']):
        algorithm_functions.append('Descriptive')
    if any(keyword in description for keyword in ['recommend', 'suggest', 'assist', 'educate', 'consult', 'advise']):
        algorithm_functions.append('Assistive')
    if any(keyword in description for keyword in ['predict', 'forecast', 'future', 'anticipate']):
        algorithm_functions.append('Predictive')
    if any(keyword in description for keyword in ['decision', 'recommendation', 'prescribe', 'diagnose', 'assess', 'examine', 'treat']):
        algorithm_functions.append('Prescriptive')
    if any(keyword in description for keyword in ['automate', 'operate', 'machine', 'monitor', 'administer', 'feed', 'clean', 'exercise', 'maintain']):
        algorithm_functions.append('Automation')
    if any(keyword in description for keyword in ['manage', 'support', 'execute', 'develop', 'evaluate', 'repair', 'install']):
        algorithm_functions.append('Support EF')

    # If no functions are matched, assign 'Unknown'
    if not algorithm_functions:
        algorithm_functions.append('Unknown')

    return algorithm_functions

# Apply the mapping function to the dataset
df['algorithm_functions'] = df['processed_description'].apply(map_algorithm_function)

# View the results with multiple algorithm functions
print(df[['Tasks', 'algorithm_functions']])

# Save the results
df.to_csv('mapped_occupational_data_with_multiple_functions.csv', index=False)

import pandas as pd

# Load the Excel file (replace 'algorithm_data.xlsx' with your file name)
df = pd.read_excel('/content/sample_data/algorithm data 2.xlsx')

# Define a function to map keywords to algorithm functions
def map_algorithm_function(description):
    description = description.lower()

    # Initialize an empty list for storing identified functions
    algorithm_functions = []

    if any(keyword in description for keyword in ['analyze', 'summarize', 'report', 'aggregate', 'visualize',
            'describe', 'measure', 'track', 'monitor', 'statistics',
            'dashboard', 'metrics', 'kpi', 'trend', 'pattern']):
        algorithm_functions.append('Descriptive')

    if any(keyword in description for keyword in ['recommend', 'assist', 'support', 'advise', 'guide',
            'help', 'aid', 'facilitate', 'suggest', 'coach']):
        algorithm_functions.append('Assistive')

    # Add new keywords related to ensemble, classifiers, and performance for Predictive mapping
    if any(keyword in description for keyword in ['predict', 'forecast', 'estimate', 'classify', 'classification', 'regression', 'supervised', 'unsupervised', 'generative', 'probabilistic', 'machine learning', 'ml', 'decision tree', 'c4.5', 'c4.5 algorithm', 'gain ratio', 'pruning', 'overfitting', 'rules', 'tree', 'attribute', 'features', 'clustering', 'cluster', 'k-means', 'clara', 'k-medoids', 'centroid', 'medoid', 'partition', 'distance', 'training data', 'dataset', 'data points', 'features', 'supervised learning', 'unsupervised learning', 'model', 'accuracy', 'error', 'algorithm', 'outliers', 'noise', 'continuous', 'discrete', 'subset', 'sample', 'nearest', 'distance', 'neural network', 'deep learning', 'feed-forward', 'artificial neural network', 'encoder', 'decoder', 'dimension', 'dimensionality reduction', 'principal component', 'pca', 'autoencoder', 'reinforcement learning', 'q-learning', 'reinforcement', 'association rule', 'item sets', 'regularize', 'transfer learning', 'rbm', 'classifier']):
        algorithm_functions.append('Predictive')

    if any(keyword in description for keyword in ['optimize', 'prescribe', 'decision-making', 'recommend solution',
            'optimization', 'scheduling', 'resource allocation', 'constraint',
            'maximization', 'minimization', 'linear programming']):
        algorithm_functions.append('Prescriptive')

    if any(keyword in description for keyword in ['automate', 'automation', 'autonomous', 'self-manage',
            'workflow', 'process automation', 'robotic process', 'automated task',
            'intelligent automation']):
        algorithm_functions.append('Automation')

    if any(keyword in description for keyword in ['enhance', 'support ef', 'executive function', 'cognitive support',
            'memory aid', 'planning support', 'organization support',
            'time management', 'task management']):
        algorithm_functions.append('Support EF')

    # If no keywords are matched, assign 'Unknown'
    if not algorithm_functions:
        algorithm_functions.append('Unknown')

    return ', '.join(algorithm_functions)

# Apply the mapping function to the 'Description' column
df['Mapped Algorithm Function'] = df['Description'].apply(map_algorithm_function)

# Display the updated DataFrame
print(df[['Algorithm ', 'Mapped Algorithm Function']])

# Save the result to a new Excel file
df.to_excel('algorithm_mapped_functions.xlsx', index=False)